#!/usr/bin/env python3
"""Generate per-agent output from the canonical sources in .agents/.

Usage:
  python3 scripts/build.py             # write dist/, plugin manifests
  python3 scripts/build.py --check     # exit 1 if generated output is stale
  python3 scripts/build.py --validate  # lint the canonical sources only
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / ".agents"
DIST = "dist"
PLUGIN_NAME = "arsenal"
MARKETPLACE_NAME = "senior-developer-arsenal"
OWNER = "Abdulazeem Mohammed"
DESCRIPTION = (
    "Senior engineering skills, subagents and rules for Node.js, .NET, Python, "
    "SQL, frontend, security, testing and DevOps."
)

NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
BANK_PLACEHOLDER = "{{BANK_ID}}"
MAX_DESCRIPTION = 1024
MAX_RULE_CHARS = 12000
MAX_AGENTS_MD_BYTES = 32 * 1024
MAX_FILE_LINES = 1000
# Hand-written sources held to the arsenal's own 1000-line file cap.
LINE_CAPPED_PATHS = (".agents", "scripts", "tests", "install.sh", "install.ps1", "AGENTS.md", "README.md")
RULE_TRIGGERS = {"always_on", "model_decision", "glob", "manual"}
SKILL_KEYS = {"name", "description", "license", "compatibility", "metadata", "allowed-tools"}
LINK_RE = re.compile(r"\]\(([^)\s]+)\)")
MD_NOTICE = "<!-- Generated by scripts/build.py from .agents/. Do not edit. -->"

# Targets that discover skills in ~/.agents/skills and <project>/.agents/skills.
SHARED_SKILL_TARGETS = ("gemini", "codex", "opencode", "cursor", "windsurf", "copilot")
# Targets that only learn about rules through the AGENTS.md index.
INDEXED_RULE_TARGETS = ("codex", "opencode")
TARGETS = ("antigravity", "gemini", "claude", "codex", "opencode", "cursor", "windsurf", "copilot")

# target -> (agent file extension, global dir, project dir)
AGENT_DESTINATIONS = {
    "antigravity": (".md", ".gemini/config/agents", ".agents/agents"),
    "gemini": (".md", ".gemini/agents", ".gemini/agents"),
    "codex": (".toml", ".codex/agents", ".codex/agents"),
    "opencode": (".md", ".config/opencode/agents", ".opencode/agents"),
    "cursor": (".md", ".cursor/agents", ".cursor/agents"),
    "copilot": (".agent.md", ".copilot/agents", ".github/agents"),
}

# target -> scope -> list of (config file, root key, snippet flavor)
MCP_DESTINATIONS = {
    "antigravity": {
        "global": [(".gemini/config/mcp_config.json", "mcpServers", "serverurl")],
        "project": [(".agents/mcp_config.json", "mcpServers", "serverurl")],
    },
    "gemini": {
        "global": [(".gemini/settings.json", "mcpServers", "gemini")],
        "project": [(".gemini/settings.json", "mcpServers", "gemini")],
    },
    "claude": {"project": [(".mcp.json", "mcpServers", "standard")]},
    "codex": {
        "global": [(".codex/config.toml", "mcp_servers", "codex")],
        "project": [(".codex/config.toml", "mcp_servers", "codex")],
    },
    "opencode": {
        "global": [(".config/opencode/opencode.json", "mcp", "opencode")],
        "project": [("opencode.json", "mcp", "opencode")],
    },
    "cursor": {
        "global": [(".cursor/mcp.json", "mcpServers", "cursor")],
        "project": [(".cursor/mcp.json", "mcpServers", "cursor")],
    },
    "windsurf": {"global": [(".codeium/windsurf/mcp_config.json", "mcpServers", "serverurl")]},
    "copilot": {
        "global": [(".copilot/mcp-config.json", "mcpServers", "copilot-cli")],
        "project": [(".vscode/mcp.json", "servers", "vscode")],
    },
}
# Older Antigravity builds read this file; it is updated only when it already exists.
ANTIGRAVITY_LEGACY_MCP = (".gemini/antigravity/mcp.json", "mcpServers", "serverurl")


class SourceError(Exception):
    """A canonical source file violates the arsenal format."""


def yaml_str(value):
    """JSON string literals are valid YAML and TOML basic strings."""
    return json.dumps(value, ensure_ascii=False)


def split_frontmatter(text, path):
    if not text.startswith("---\n"):
        raise SourceError(f"{path}: missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SourceError(f"{path}: unterminated YAML frontmatter")
    return text[4:end], text[end + 5:].lstrip("\n")


def parse_frontmatter(block, path):
    """Parse the flat `key: 'single-quoted'` subset the arsenal sources use."""
    data = {}
    for line in block.splitlines():
        if not line.strip():
            continue
        match = re.match(r"^([A-Za-z][A-Za-z0-9_-]*): (.*)$", line)
        if not match:
            raise SourceError(f"{path}: unsupported frontmatter line: {line!r}")
        key, raw = match.groups()
        if raw.startswith("'"):
            if len(raw) < 2 or not raw.endswith("'") or "'" in raw[1:-1].replace("''", ""):
                raise SourceError(f"{path}: '{key}' has an unbalanced single quote")
            value = raw[1:-1].replace("''", "'")
        elif re.search(r": |^[\"\[{>|&*!%@`#]| #", raw):
            raise SourceError(f"{path}: '{key}' must be wrapped in single quotes")
        else:
            value = raw
        if key in data:
            raise SourceError(f"{path}: duplicate frontmatter key '{key}'")
        data[key] = value
    return data


def read(path):
    text = path.read_text(encoding="utf-8")
    if "\r" in text:
        raise SourceError(f"{path.relative_to(ROOT)}: contains CRLF line endings")
    return text


def load_skills():
    skills = []
    for directory in sorted(p for p in (AGENTS / "skills").iterdir() if p.is_dir()):
        skill_file = directory / "SKILL.md"
        rel = skill_file.relative_to(ROOT)
        if not skill_file.is_file():
            raise SourceError(f"{rel}: missing")
        text = read(skill_file)
        block, body = split_frontmatter(text, rel)
        meta = parse_frontmatter(block, rel)
        unknown = set(meta) - SKILL_KEYS
        if unknown:
            raise SourceError(f"{rel}: unsupported frontmatter keys {sorted(unknown)}")
        name, description = meta.get("name", ""), meta.get("description", "")
        if name != directory.name:
            raise SourceError(f"{rel}: name '{name}' does not match folder '{directory.name}'")
        if not NAME_RE.match(name):
            raise SourceError(f"{rel}: name must match {NAME_RE.pattern}")
        if not 1 <= len(description) <= MAX_DESCRIPTION:
            raise SourceError(f"{rel}: description must be 1-{MAX_DESCRIPTION} characters")
        for markdown in sorted(directory.rglob("*.md")):
            check_links(markdown, directory)
        skills.append(name)
    if not skills:
        raise SourceError(".agents/skills: no skills found")
    return skills


def check_links(markdown, skill_dir):
    for target in LINK_RE.findall(read(markdown)):
        if re.match(r"^([a-z][a-z0-9+.-]*:|#)", target) or "{{" in target:
            continue
        resolved = (markdown.parent / target.split("#")[0]).resolve()
        rel = markdown.relative_to(ROOT)
        if skill_dir.resolve() not in resolved.parents:
            raise SourceError(f"{rel}: link '{target}' leaves the skill folder")
        if not resolved.exists():
            raise SourceError(f"{rel}: link '{target}' does not resolve")


def load_rules():
    rules = []
    for rule_file in sorted((AGENTS / "rules").glob("*.md")):
        rel = rule_file.relative_to(ROOT)
        text = read(rule_file)
        if len(text) > MAX_RULE_CHARS:
            raise SourceError(f"{rel}: exceeds {MAX_RULE_CHARS} characters")
        block, body = split_frontmatter(text, rel)
        meta = parse_frontmatter(block, rel)
        trigger = meta.get("trigger")
        if trigger not in RULE_TRIGGERS:
            raise SourceError(f"{rel}: trigger must be one of {sorted(RULE_TRIGGERS)}")
        if not meta.get("description"):
            raise SourceError(f"{rel}: description is required")
        globs = [g.strip() for g in meta.get("globs", "").split(",") if g.strip()]
        if (trigger == "glob") != bool(globs):
            raise SourceError(f"{rel}: globs must be set exactly when trigger is 'glob'")
        rules.append({
            "name": rule_file.stem, "trigger": trigger,
            "description": meta["description"], "globs": globs, "body": body,
        })
    if not rules:
        raise SourceError(".agents/rules: no rules found")
    return rules


def load_subagents():
    manifest = AGENTS / "subagents" / "subagent-definitions.json"
    definitions = json.loads(read(manifest))["subagents"]
    subagents, seen = [], set()
    for entry in definitions:
        name = entry.get("name", "")
        if not NAME_RE.match(name) or name in seen:
            raise SourceError(f"subagent-definitions.json: invalid or duplicate name '{name}'")
        seen.add(name)
        if not entry.get("description"):
            raise SourceError(f"subagent-definitions.json: '{name}' has no description")
        if entry.get("recommended_model") not in ("pro", "inherit"):
            raise SourceError(f"subagent-definitions.json: '{name}' has an unknown recommended_model")
        if not isinstance(entry.get("enable_write_tools"), bool):
            raise SourceError(f"subagent-definitions.json: '{name}' enable_write_tools must be a boolean")
        prompt = (manifest.parent / entry.get("promptFile", "")).resolve()
        if prompt != (manifest.parent / "prompts" / f"{name}.md").resolve() or not prompt.is_file():
            raise SourceError(f"subagent-definitions.json: '{name}' promptFile must be ./prompts/{name}.md")
        body = read(prompt).strip()
        if not body or body.startswith("---"):
            raise SourceError(f"prompts/{name}.md: must be non-empty plain markdown without frontmatter")
        subagents.append({
            "name": name, "description": entry["description"], "body": body,
            "writes": entry["enable_write_tools"], "pro": entry["recommended_model"] == "pro",
        })
    return subagents


def load_servers():
    servers = json.loads(read(AGENTS / "mcp" / "servers.json"))
    for name, spec in servers.items():
        if not NAME_RE.match(name):
            raise SourceError(f"servers.json: invalid server name '{name}'")
        if spec.get("type") == "stdio":
            if not isinstance(spec.get("command"), str) or not isinstance(spec.get("args", []), list):
                raise SourceError(f"servers.json: '{name}' needs a command string and args list")
        elif spec.get("type") == "http":
            if not str(spec.get("url", "")).startswith("http"):
                raise SourceError(f"servers.json: '{name}' needs an http(s) url")
        else:
            raise SourceError(f"servers.json: '{name}' type must be 'stdio' or 'http'")
    return servers


def check_line_cap():
    for entry in LINE_CAPPED_PATHS:
        path = ROOT / entry
        files = [path] if path.is_file() else sorted(p for p in path.rglob("*") if p.is_file())
        for file in files:
            if "__pycache__" in file.parts:
                continue
            lines = file.read_bytes().count(b"\n")
            if lines > MAX_FILE_LINES:
                raise SourceError(f"{file.relative_to(ROOT)}: {lines} lines exceeds the {MAX_FILE_LINES}-line cap")


def load_sources():
    check_line_cap()
    agents_md = ROOT / "AGENTS.md"
    if len(agents_md.read_bytes()) > MAX_AGENTS_MD_BYTES:
        raise SourceError(f"AGENTS.md: exceeds {MAX_AGENTS_MD_BYTES} bytes (Codex instruction cap)")
    version = read(ROOT / "VERSION").strip()
    if not re.match(r"^\d+\.\d+\.\d+$", version):
        raise SourceError("VERSION: must be MAJOR.MINOR.PATCH")
    return {
        "skills": load_skills(), "rules": load_rules(), "subagents": load_subagents(),
        "servers": load_servers(), "version": version,
    }


def markdown_agent(fields, body):
    lines = ["---"] + [f"{key}: {value}".rstrip() for key, value in fields] + ["---", "", MD_NOTICE, "", body, ""]
    return "\n".join(lines)


def render_agent(target, agent):
    name, description = yaml_str(agent["name"]), yaml_str(agent["description"])
    if target == "claude":
        fields = [("name", name), ("description", description), ("model", "inherit")]
        if not agent["writes"]:
            fields.append(("disallowedTools", "Write, Edit, NotebookEdit"))
    elif target == "cursor":
        fields = [("name", name), ("description", description), ("model", "inherit"),
                  ("readonly", "false" if agent["writes"] else "true")]
    elif target == "opencode":
        fields = [("description", description), ("mode", "subagent")]
        if not agent["writes"]:
            fields += [("permission", ""), ("  edit", "deny")]
    elif target == "copilot":
        fields = [("name", name), ("description", description)]
        if not agent["writes"]:
            fields.append(("tools", '["read", "search", "execute", "web"]'))
    elif target == "antigravity":
        fields = [("name", name), ("description", description),
                  ("model", "pro" if agent["pro"] else "inherit")]
    elif target == "gemini":
        fields = [("name", name), ("description", description)]
    elif target == "codex":
        lines = ["# Generated by scripts/build.py from .agents/. Do not edit.",
                 f"name = {name}", f"description = {description}"]
        if agent["pro"]:
            lines.append('model_reasoning_effort = "high"')
        if not agent["writes"]:
            lines.append('sandbox_mode = "read-only"')
        lines.append(f"developer_instructions = {yaml_str(agent['body'])}")
        return "\n".join(lines) + "\n"
    else:
        raise ValueError(target)
    return markdown_agent(fields, agent["body"])


def render_rule(target, rule):
    always = rule["trigger"] == "always_on"
    globs = ",".join(rule["globs"])
    if target == "claude":
        if not rule["globs"]:
            return f"{MD_NOTICE}\n\n{rule['body']}"
        fields = ["paths:"] + [f"  - {yaml_str(glob)}" for glob in rule["globs"]]
    elif target == "cursor":
        fields = [f"description: {yaml_str(rule['description'])}"]
        if rule["globs"]:
            fields.append(f"globs: {globs}")
        fields.append(f"alwaysApply: {'true' if always else 'false'}")
    elif target == "copilot":
        fields = [f"applyTo: {yaml_str(globs or '**')}"]
    else:
        raise ValueError(target)
    return "\n".join(["---"] + fields + ["---", "", MD_NOTICE, "", rule["body"]])


def render_mcp(flavor, spec):
    """Return one server entry in the shape a given MCP client expects."""
    stdio = spec["type"] == "stdio"
    command, args, url = spec.get("command"), spec.get("args", []), spec.get("url")
    if flavor == "codex":
        if stdio:
            return f"command = {yaml_str(command)}\nargs = {json.dumps(args)}\n"
        return f"url = {yaml_str(url)}\n"
    if flavor == "standard":
        entry = {"command": command, "args": args} if stdio else {"type": "http", "url": url}
    elif flavor == "cursor":
        entry = {"command": command, "args": args} if stdio else {"url": url}
    elif flavor == "serverurl":
        entry = {"command": command, "args": args} if stdio else {"serverUrl": url}
    elif flavor == "gemini":
        entry = {"command": command, "args": args} if stdio else {"httpUrl": url}
    elif flavor == "vscode":
        entry = {"type": "stdio", "command": command, "args": args} if stdio else {"type": "http", "url": url}
    elif flavor == "copilot-cli":
        entry = ({"type": "local", "command": command, "args": args, "tools": ["*"]} if stdio
                 else {"type": "http", "url": url, "tools": ["*"]})
    elif flavor == "opencode":
        entry = ({"type": "local", "command": [command, *args], "enabled": True} if stdio
                 else {"type": "remote", "url": url, "enabled": True})
    else:
        raise ValueError(flavor)
    return json.dumps(entry, indent=2) + "\n"


def manifest_rows(sources):
    """Rows of target, scope, kind, name, source, destination, extra.

    Destinations are relative to $HOME (global) or the project root (project).
    Unused fields hold "-" so shells that collapse empty tab fields parse it.
    """
    rows = []

    def add(target, scope, kind, name, source="-", destination="-", extra="-"):
        rows.append((target, scope, kind, name, source, destination, extra))

    for target in TARGETS:
        for scope in ("global", "project"):
            is_global = scope == "global"
            if target == "antigravity":
                skills_dir = ".gemini/config/skills" if is_global else ".agents/skills"
            elif target in SHARED_SKILL_TARGETS:
                skills_dir = ".agents/skills"
            else:
                skills_dir = None
            if skills_dir:
                for skill in sources["skills"]:
                    add(target, scope, "dir", skill, f".agents/skills/{skill}", f"{skills_dir}/{skill}")

            if target in AGENT_DESTINATIONS:
                extension, global_dir, project_dir = AGENT_DESTINATIONS[target]
                for agent in sources["subagents"]:
                    filename = agent["name"] + extension
                    add(target, scope, "file", filename, f"{DIST}/{target}/agents/{filename}",
                        f"{global_dir if is_global else project_dir}/{filename}")

            for rule in sources["rules"]:
                canonical, name = f".agents/rules/{rule['name']}.md", rule["name"]
                if target == "antigravity":
                    directory = ".gemini/config/rules" if is_global else ".agents/rules"
                    add(target, scope, "file", f"{name}.md", canonical, f"{directory}/{name}.md")
                elif target == "claude":
                    add(target, scope, "file", f"{name}.md", f"{DIST}/claude/rules/{name}.md",
                        f".claude/rules/arsenal/{name}.md")
                elif target in INDEXED_RULE_TARGETS:
                    add(target, scope, "file", f"{name}.md", canonical, f".agents/rules/{name}.md")
                elif is_global:
                    continue
                elif target == "cursor":
                    add(target, scope, "file", f"{name}.mdc", f"{DIST}/cursor/rules/{name}.mdc",
                        f".cursor/rules/{name}.mdc")
                elif target == "windsurf":
                    add(target, scope, "file", f"{name}.md", canonical, f".windsurf/rules/{name}.md")
                elif target == "copilot":
                    filename = f"{name}.instructions.md"
                    add(target, scope, "file", filename, f"{DIST}/copilot/instructions/{filename}",
                        f".github/instructions/{filename}")

            if not is_global:
                add(target, scope, "block", "AGENTS.md", "AGENTS.md", "AGENTS.md")
                if target == "claude":
                    add(target, scope, "block", "CLAUDE.md", f"{DIST}/claude/CLAUDE.block.md", "CLAUDE.md")
                if target == "gemini":
                    add(target, scope, "block", "GEMINI.md", f"{DIST}/gemini/GEMINI.block.md", "GEMINI.md")
            elif target == "codex":
                add(target, scope, "block", "AGENTS.md", "AGENTS.md", ".codex/AGENTS.md")
            elif target == "opencode":
                add(target, scope, "block", "AGENTS.md", "AGENTS.md", ".config/opencode/AGENTS.md")

            destinations = list(MCP_DESTINATIONS[target].get(scope, []))
            for server in sources["servers"]:
                for config, key, flavor in destinations:
                    fmt = "toml" if flavor == "codex" else "json"
                    add(target, scope, "mcp", server, f"{DIST}/mcp/{flavor}/{server}.{fmt}", config, f"{key}:{fmt}")
                if target == "antigravity" and is_global:
                    config, key, flavor = ANTIGRAVITY_LEGACY_MCP
                    add(target, scope, "mcp-if-exists", server, f"{DIST}/mcp/{flavor}/{server}.json",
                        config, f"{key}:json")
                if not destinations:
                    hint = (f"Claude Code: run /plugin install {PLUGIN_NAME}-{server}@{MARKETPLACE_NAME}"
                            if target == "claude" else
                            f"{target} has no {scope}-level MCP config file; use the other scope for '{server}'.")
                    add(target, scope, "mcp-note", server, extra=hint)

        if target == "claude":
            for scope in ("global", "project"):
                add(target, scope, "note", "plugin", extra=(
                    "Skills and subagents load through the Claude Code plugin: "
                    f"/plugin marketplace add <path-or-repo> then /plugin install {PLUGIN_NAME}@{MARKETPLACE_NAME}"))
    return rows


def generate(sources):
    """Return {repo-relative path: text} for every generated file."""
    out = {}
    for agent in sources["subagents"]:
        for target, (extension, _, _) in AGENT_DESTINATIONS.items():
            out[f"{DIST}/{target}/agents/{agent['name']}{extension}"] = render_agent(target, agent)
        out[f"{DIST}/claude/agents/{agent['name']}.md"] = render_agent("claude", agent)
    for rule in sources["rules"]:
        out[f"{DIST}/claude/rules/{rule['name']}.md"] = render_rule("claude", rule)
        out[f"{DIST}/cursor/rules/{rule['name']}.mdc"] = render_rule("cursor", rule)
        out[f"{DIST}/copilot/instructions/{rule['name']}.instructions.md"] = render_rule("copilot", rule)
    out[f"{DIST}/claude/CLAUDE.block.md"] = "@AGENTS.md\n"
    out[f"{DIST}/gemini/GEMINI.block.md"] = "@./AGENTS.md\n"

    flavors = sorted({flavor for scopes in MCP_DESTINATIONS.values() for entries in scopes.values()
                      for _, _, flavor in entries})
    for name, spec in sources["servers"].items():
        for flavor in flavors:
            extension = "toml" if flavor == "codex" else "json"
            out[f"{DIST}/mcp/{flavor}/{name}.{extension}"] = render_mcp(flavor, spec)
        plugin_spec = dict(spec)
        if "url" in plugin_spec:
            plugin_spec["url"] = plugin_spec["url"].replace(BANK_PLACEHOLDER, "${HINDSIGHT_BANK_ID:-default}")
        base = f"plugins/{name}"
        out[f"{base}/.mcp.json"] = json.dumps(
            {"mcpServers": {name: json.loads(render_mcp("standard", plugin_spec))}}, indent=2) + "\n"
        out[f"{base}/.claude-plugin/plugin.json"] = json.dumps({
            "name": f"{PLUGIN_NAME}-{name}", "version": sources["version"],
            "description": f"Registers the {name} MCP server for the Senior Developer Arsenal.",
            "author": {"name": OWNER}, "license": "MIT",
        }, indent=2) + "\n"

    out[".claude-plugin/plugin.json"] = json.dumps({
        "name": PLUGIN_NAME, "version": sources["version"], "description": DESCRIPTION,
        "author": {"name": OWNER}, "license": "MIT",
        "skills": ["./.agents/skills/"],
        "agents": [f"./{DIST}/claude/agents/{agent['name']}.md" for agent in sources["subagents"]],
    }, indent=2) + "\n"
    out[".claude-plugin/marketplace.json"] = json.dumps({
        "name": MARKETPLACE_NAME, "owner": {"name": OWNER}, "description": DESCRIPTION,
        "plugins": [{"name": PLUGIN_NAME, "source": "./", "description": DESCRIPTION}] + [
            {"name": f"{PLUGIN_NAME}-{name}", "source": f"./plugins/{name}",
             "description": f"Optional {name} MCP server."} for name in sources["servers"]],
    }, indent=2) + "\n"

    header = "target\tscope\tkind\tname\tsource\tdestination\textra\n"
    out[f"{DIST}/manifest.tsv"] = header + "".join("\t".join(row) + "\n" for row in manifest_rows(sources))
    return out


def generated_roots():
    return [ROOT / DIST, ROOT / "plugins", ROOT / ".claude-plugin"]


def existing_generated_files():
    return {
        path.relative_to(ROOT).as_posix()
        for root in generated_roots() if root.exists()
        for path in root.rglob("*") if path.is_file()
    }


def stale_paths(expected):
    """Paths whose on-disk state differs from the expected generated output."""
    stale = sorted(existing_generated_files() - set(expected))
    for relative, text in sorted(expected.items()):
        path = ROOT / relative
        if not path.is_file() or path.read_bytes() != text.encode("utf-8"):
            stale.append(relative)
    return stale


def write(expected):
    for relative in existing_generated_files() - set(expected):
        (ROOT / relative).unlink()
    for relative, text in expected.items():
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))
    for root in generated_roots():
        for directory in sorted((p for p in root.rglob("*") if p.is_dir()), reverse=True):
            if not any(directory.iterdir()):
                directory.rmdir()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if generated output is stale")
    mode.add_argument("--validate", action="store_true", help="lint canonical sources only")
    options = parser.parse_args(argv)

    try:
        sources = load_sources()
    except (SourceError, OSError, ValueError, KeyError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    summary = (f"{len(sources['skills'])} skills, {len(sources['subagents'])} subagents, "
               f"{len(sources['rules'])} rules, {len(sources['servers'])} MCP servers")
    if options.validate:
        print(f"valid: {summary}")
        return 0

    expected = generate(sources)
    if options.check:
        stale = stale_paths(expected)
        if stale:
            print("stale generated files (run python3 scripts/build.py):", file=sys.stderr)
            for relative in stale:
                print(f"  {relative}", file=sys.stderr)
            return 1
        print(f"up to date: {summary}")
        return 0

    write(expected)
    print(f"generated {len(expected)} files from {summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
